services:
  isep-ics:
    build: .
    container_name: isep-ics
    environment:
      # Non-sensitive configuration
      ISEP_BASE_URL: "https://portal.isep.ipp.pt"
      ISEP_CODE_USER: "YOUR_STUDENT_CODE"
      ISEP_CODE_USER_CODE: "YOUR_STUDENT_CODE"
      ISEP_ENTIDADE: "aluno"
      ISEP_FETCH_WEEKS_BEFORE: "0"
      ISEP_FETCH_WEEKS_AFTER: "6"
      ISEP_REFRESH_MINUTES: "15"
      TZ: "Europe/Lisbon"
      PORT: "8080"
      # Sensitive data from Docker secrets
      ISEP_USERNAME_FILE: "/run/secrets/isep_username"
      ISEP_PASSWORD_FILE: "/run/secrets/isep_password"
    secrets:
      - isep_username
      - isep_password
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bun", "--bun", "run", "-e", "fetch('http://localhost:8080/healthz').then(r => r.ok ? process.exit(0) : process.exit(1)).catch(() => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

secrets:
  isep_username:
    file: ./secrets/isep_username.txt
  isep_password:
    file: ./secrets/isep_password.txt
