services:
  isep-ics:
    build: .
    container_name: isep-ics
    env_file:
      - .env
    environment:
      # Non-sensitive configuration (can be overridden)
      ISEP_BASE_URL: "https://portal.isep.ipp.pt"
      ISEP_ENTIDADE: "aluno"
      ISEP_FETCH_WEEKS_BEFORE: "0"
      ISEP_FETCH_WEEKS_AFTER: "6"
      ISEP_REFRESH_MINUTES: "15"
      TZ: "Europe/Lisbon"
      PORT: "4321"
    ports:
      - "4321:4321"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bun", "--bun", "run", "-e", "fetch('http://localhost:4321/healthz').then(r => r.ok ? process.exit(0) : process.exit(1)).catch(() => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s